server.port=8080
spring.application.name=backform
spring.datasource.url=jdbc:mysql://localhost:3306/heritage_culture_site?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:MySQL_Dolphin}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.sql.init.mode=never
app.auth.token-expire-minutes=120
app.captcha.expire-minutes=5
app.seed.fix-demo-passwords=true

mybatis.mapper-locations=classpath*:mapper/*.xml
mybatis.configuration.map-underscore-to-camel-case=true
app.cors.allowed-origins=http://localhost:5173
