<template><section class="container"><div v-if="loading" class="loading">加载中...</div><div v-else-if="error" class="error">{{error}}</div><article v-else><h2>{{article.title}}</h2><p>{{article.summary}}</p><img v-if="article.coverUrl" :src="article.coverUrl"/><div v-html="article.content"></div><ul><li v-for="s in article.sources||[]" :key="s.id"><a :href="s.sourceUrl" target="_blank">{{s.sourceTitle}}</a></li></ul><div class="page-actions"><span>浏览{{article.viewCount||0}} 点赞{{article.likeCount||0}} 评论{{article.commentCount||0}} 转发{{article.shareCount||0}}</span><button @click="toggleLike">{{article.likedByCurrentUser?'取消点赞':'点赞'}}</button></div><div><textarea v-model="comment" placeholder="请输入评论"/><button @click="submitComment">发表评论</button></div><p v-if="msg" class="message-box">{{msg}}</p><SharePanel :article-id="article.id" @shared="refreshDetail"/><CommentList ref="listRef" :article-id="article.id"/></article></section></template>
<script setup>
import { computed, onMounted, ref } from 'vue'; import { useRoute } from 'vue-router'; import { createComment,getArticleDetail,likeArticle,recordView,unlikeArticle } from '../api/article'; import CommentList from '../components/CommentList.vue'; import SharePanel from '../components/SharePanel.vue'
const route=useRoute(); const slug=computed(()=>route.params.slug); const loading=ref(false); const error=ref(''); const article=ref({}); const msg=ref(''); const comment=ref(''); const listRef=ref()
const refreshDetail=async()=>{article.value=await getArticleDetail(slug.value)}
const load=async()=>{loading.value=true; error.value=''; try{await refreshDetail(); if(article.value?.id){const c=await recordView(article.value.id); article.value={...article.value,...c}}}catch(e){error.value=e.message}finally{loading.value=false}}
const toggleLike=async()=>{try{const fn=article.value.likedByCurrentUser?unlikeArticle:likeArticle; const c=await fn(article.value.id); article.value={...article.value,...c,likedByCurrentUser:!article.value.likedByCurrentUser}}catch(e){msg.value=e.message}}
const submitComment=async()=>{if(!comment.value.trim())return; try{await createComment(article.value.id,comment.value); comment.value=''; msg.value='评论成功'; await listRef.value?.load(); await refreshDetail()}catch(e){msg.value=e.message}}
onMounted(load)
</script>
